name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore BokningsAppDevOpsCleanCode.sln
      working-directory: BokningsAppDevOpsCleanCode

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: BokningsAppDevOpsCleanCode
