name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore BokningsAppDevOpsCleanCode.UnitTests/BokningsAppDevOpsCleanCode.UnitTests.csproj
      working-directory: BokningsAppDevOpsCleanCode

    - name: Build
      run: dotnet build --configuration Release --no-restore BokningsAppDevOpsCleanCode.UnitTests/BokningsAppDevOpsCleanCode.UnitTests.csproj
      working-directory: BokningsAppDevOpsCleanCode

    - name: Run Tests
      run: dotnet test --configuration Release --no-build BokningsAppDevOpsCleanCode.UnitTests/BokningsAppDevOpsCleanCode.UnitTests.csproj
      working-directory: BokningsAppDevOpsCleanCode

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/TestResults/*.xml'

