name: Build Project

on:
  push:
    branches:
      
main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

- name: Set up .NET
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1'

- name: Change to project directory
  run: cd path/to/your/project

- name: Restore dependencies
  run: dotnet restore BokningsAppDevOpsCleanCode.sln

- name: Build
  run: dotnet build --configuration Release

- name: Run Tests
  run: dotnet test --no-build --configuration Release --filter FullyQualifiedName~BokningsAppDevOpsCleanCode.UnitTests.BookingServiceTests
  working-directory: BokningsAppDevOpsCleanCode


